using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Fernando
{
    public class BaseDatos
    {
        public Materia[] Materias
        {
            get { return _Materias; }
        }

        public Profesor[] Teachers
        {
            get { return _teachers; }
        }

        private static Materia[] _Materias = new Materia[]
        {
            new Materia { Id = 1, TeacherId = 6, Nombre = "Medical-Surgical" },
            new Materia { Id = 2, TeacherId = 20, Nombre = "Consumer Behaviour" },
            new Materia { Id = 3, TeacherId = 24, Nombre = "HSM" },
            new Materia { Id = 4, TeacherId = 24, Nombre = "Bathrooms" },
            new Materia { Id = 5, TeacherId = 27, Nombre = "MRO Management" },
            new Materia { Id = 6, TeacherId = 9, Nombre = "DLC" },
            new Materia { Id = 7, TeacherId = 16, Nombre = "Commercial Awareness" },
            new Materia { Id = 8, TeacherId = 1, Nombre = "KDB+" },
            new Materia { Id = 9, TeacherId = 29, Nombre = "Townhomes" },
            new Materia { Id = 10, TeacherId = 21, Nombre = "WLM" },
            new Materia { Id = 11, TeacherId = 24, Nombre = "AHU" },
            new Materia { Id = 12, TeacherId = 21, Nombre = "Equipment Repair" },
            new Materia { Id = 13, TeacherId = 15, Nombre = "iPod" },
            new Materia { Id = 14, TeacherId = 5, Nombre = "HAZOP Study" },
            new Materia { Id = 15, TeacherId = 18, Nombre = "HR Consulting" },
            new Materia { Id = 16, TeacherId = 11, Nombre = "Errors &amp; Omissions" },
            new Materia { Id = 17, TeacherId = 29, Nombre = "PMBOK" },
            new Materia { Id = 18, TeacherId = 17, Nombre = "Xoops" },
            new Materia { Id = 19, TeacherId = 29, Nombre = "sFlow" },
            new Materia { Id = 20, TeacherId = 11, Nombre = "PPBES" },
            new Materia { Id = 21, TeacherId = 14, Nombre = "RPR" },
            new Materia { Id = 22, TeacherId = 16, Nombre = "Group Therapy" },
            new Materia { Id = 23, TeacherId = 4, Nombre = "BGAN" },
            new Materia { Id = 24, TeacherId = 5, Nombre = "Legal Advice" },
            new Materia { Id = 25, TeacherId = 15, Nombre = "DWR" },
            new Materia { Id = 26, TeacherId = 30, Nombre = "Talent Acquisition" },
            new Materia { Id = 27, TeacherId = 20, Nombre = "HTFS" },
            new Materia { Id = 28, TeacherId = 16, Nombre = "Juniper Technologies" },
            new Materia { Id = 29, TeacherId = 9, Nombre = "DHS" },
            new Materia { Id = 30, TeacherId = 29, Nombre = "GL" },
            new Materia { Id = 31, TeacherId = 1, Nombre = "Executive Protection" },
            new Materia { Id = 32, TeacherId = 25, Nombre = "Vital Signs" },
            new Materia { Id = 33, TeacherId = 18, Nombre = "Fixed Income" },
            new Materia { Id = 34, TeacherId = 18, Nombre = "Eclipse" },
            new Materia { Id = 35, TeacherId = 16, Nombre = "Sleep Disorders" },
            new Materia { Id = 36, TeacherId = 18, Nombre = "SFR Certified" },
            new Materia { Id = 37, TeacherId = 13, Nombre = "AutoCAD Architecture" },
            new Materia { Id = 38, TeacherId = 28, Nombre = "Behavioral Health" },
            new Materia { Id = 39, TeacherId = 5, Nombre = "Pension Funds" },
            new Materia { Id = 40, TeacherId = 22, Nombre = "HMC" },
            new Materia { Id = 41, TeacherId = 10, Nombre = "VDSL" },
            new Materia { Id = 42, TeacherId = 1, Nombre = "Full SDLC" },
            new Materia { Id = 43, TeacherId = 24, Nombre = "Dunn &amp; Bradstreet" },
            new Materia { Id = 44, TeacherId = 6, Nombre = "SV" },
            new Materia { Id = 45, TeacherId = 30, Nombre = "XATA" },
            new Materia { Id = 46, TeacherId = 24, Nombre = "Software Quality Assurance" },
            new Materia { Id = 47, TeacherId = 22, Nombre = "Behavior Based Safety" },
            new Materia { Id = 48, TeacherId = 18, Nombre = "Scanning Electron Microscopy" },
            new Materia { Id = 49, TeacherId = 28, Nombre = "Pallet Jack" },
            new Materia { Id = 50, TeacherId = 2, Nombre = "Go-to-market Strategy" },
            new Materia { Id = 51, TeacherId = 15, Nombre = "NCS" },
            new Materia { Id = 52, TeacherId = 7, Nombre = "Verilog" },
            new Materia { Id = 53, TeacherId = 27, Nombre = "Legislative Affairs" },
            new Materia { Id = 54, TeacherId = 9, Nombre = "PPMS" },
            new Materia { Id = 55, TeacherId = 4, Nombre = "Economic Research" },
            new Materia { Id = 56, TeacherId = 12, Nombre = "GMLAN" },
            new Materia { Id = 57, TeacherId = 27, Nombre = "ASP.NET MVC" },
            new Materia { Id = 58, TeacherId = 30, Nombre = "Piano" },
            new Materia { Id = 59, TeacherId = 1, Nombre = "GDS systems" },
            new Materia { Id = 60, TeacherId = 15, Nombre = "AVEVA PDMS" },
            new Materia { Id = 61, TeacherId = 17, Nombre = "EOC" },
            new Materia { Id = 62, TeacherId = 4, Nombre = "Radio Broadcasting" },
            new Materia { Id = 63, TeacherId = 19, Nombre = "JAX-WS" },
            new Materia { Id = 64, TeacherId = 22, Nombre = "Jitterbit" },
            new Materia { Id = 65, TeacherId = 26, Nombre = "Business Transformation" },
            new Materia { Id = 66, TeacherId = 24, Nombre = "CCDP" },
            new Materia { Id = 67, TeacherId = 12, Nombre = "Tour Management" },
            new Materia { Id = 68, TeacherId = 13, Nombre = "Quality Assurance" },
            new Materia { Id = 69, TeacherId = 2, Nombre = "JBoss Seam" },
            new Materia { Id = 70, TeacherId = 17, Nombre = "GFI" },
            new Materia { Id = 71, TeacherId = 15, Nombre = "SSPS" },
            new Materia { Id = 72, TeacherId = 25, Nombre = "LGD" },
            new Materia { Id = 73, TeacherId = 15, Nombre = "Cycling" },
            new Materia { Id = 74, TeacherId = 19, Nombre = "Test Planning" },
            new Materia { Id = 75, TeacherId = 11, Nombre = "European Affairs" },
            new Materia { Id = 76, TeacherId = 1, Nombre = "Biblical Studies" },
            new Materia { Id = 77, TeacherId = 20, Nombre = "JDE CNC" },
            new Materia { Id = 78, TeacherId = 30, Nombre = "UltraTax CS" },
            new Materia { Id = 79, TeacherId = 9, Nombre = "IB" },
            new Materia { Id = 80, TeacherId = 19, Nombre = "FCNSP" },
            new Materia { Id = 81, TeacherId = 6, Nombre = "Hydrology" },
            new Materia { Id = 82, TeacherId = 9, Nombre = "TVC" },
            new Materia { Id = 83, TeacherId = 5, Nombre = "Sea Kayaking" },
            new Materia { Id = 84, TeacherId = 21, Nombre = "NI LabVIEW" },
            new Materia { Id = 85, TeacherId = 1, Nombre = "SSAE 16" },
            new Materia { Id = 86, TeacherId = 13, Nombre = "GNU C" },
            new Materia { Id = 87, TeacherId = 22, Nombre = "Corporate Finance" },
            new Materia { Id = 88, TeacherId = 22, Nombre = "Inventory Management" },
            new Materia { Id = 89, TeacherId = 24, Nombre = "Geometric Dimensioning &amp; Tolerancing" },
            new Materia { Id = 90, TeacherId = 29, Nombre = "Project Oversight" },
            new Materia { Id = 91, TeacherId = 29, Nombre = "Beverage Industry" },
            new Materia { Id = 92, TeacherId = 10, Nombre = "AAUS Scientific Diver" },
            new Materia { Id = 93, TeacherId = 6, Nombre = "Freelance Writing" },
            new Materia { Id = 94, TeacherId = 4, Nombre = "VLSI" },
            new Materia { Id = 95, TeacherId = 12, Nombre = "Pygame" },
            new Materia { Id = 96, TeacherId = 13, Nombre = "Online Communications" },
            new Materia { Id = 97, TeacherId = 15, Nombre = "RIP" },
            new Materia { Id = 98, TeacherId = 17, Nombre = "Skin Care Products" },
            new Materia { Id = 99, TeacherId = 13, Nombre = "UCP" },
            new Materia { Id = 100, TeacherId = 14, Nombre = "Ghostwriting" },
        };

        private static Profesor[] _teachers = new Profesor[]
        {
            new Profesor { Id = 1, Nombre= "Janet", Apellido = "Nelson", Edad = 41, Correo = "dnelson0@ft.com" },
            new Profesor { Id = 2, Nombre= "Martha", Apellido = "Brooks", Edad = 42, Correo = "mbrooks1@msu.edu" },
            new Profesor { Id = 3, Nombre= "Janice", Apellido = "Franklin", Edad = 44, Correo = "jfranklin2@cornell.edu" },
            new Profesor { Id = 4, Nombre= "Martha", Apellido = "Burke", Edad = 26, Correo = "" },
            new Profesor { Id = 5, Nombre= "Virginia", Apellido = "Williams", Edad = 50, Correo = "vwilliams4@wikispaces.com" },
            new Profesor { Id = 6, Nombre= "Jonathan", Apellido = "Graham", Edad = 44, Correo = "" },
            new Profesor { Id = 7, Nombre= "Helen", Apellido = "Snyder", Edad = 41, Correo = "hsnyder6@tuttocitta.it" },
            new Profesor { Id = 8, Nombre= "George", Apellido = "Jackson", Edad = 21, Correo = "gjackson7@apple.com" },
            new Profesor { Id = 9, Nombre= "Carol", Apellido = "Frazier", Edad = 38, Correo = "cfrazier8@taobao.com" },
            new Profesor { Id = 10, Nombre= "Janet", Apellido = "Little", Edad = 38, Correo = "" },
            new Profesor { Id = 11, Nombre= "Frank", Apellido = "Hunt", Edad = 24, Correo = "" },
            new Profesor { Id = 12, Nombre= "Carl", Apellido = "Foster", Edad = 36, Correo = "cfosterb@harvard.edu" },
            new Profesor { Id = 13, Nombre= "Margaret", Apellido = "Burton", Edad = 77, Correo = "" },
            new Profesor { Id = 14, Nombre= "Carol", Apellido = "James", Edad = 30, Correo = "cjamesd@com.com" },
            new Profesor { Id = 15, Nombre= "Shawn", Apellido = "Hanson", Edad = 40, Correo = "shansone@linkedin.com" },
            new Profesor { Id = 16, Nombre= "Eugene", Apellido = "Stevens", Edad = 18, Correo = "estevensf@g.co" },
            new Profesor { Id = 17, Nombre= "Maria", Apellido = "Myers", Edad = 23, Correo = "mmyersg@prnewswire.com" },
            new Profesor { Id = 18, Nombre= "Terry", Apellido = "Williams", Edad = 26, Correo = "tlawrenceh@wiley.com" },
            new Profesor { Id = 19, Nombre= "Phyllis", Apellido = "Burns", Edad = 33, Correo = "pburnsi@umn.edu" },
            new Profesor { Id = 20, Nombre= "Emily", Apellido = "Robertson", Edad = 35, Correo = "erobertsonj@oracle.com" },
            new Profesor { Id = 21, Nombre= "Janet", Apellido = "Gordon", Edad = 45, Correo = "cgordonk@barnesandnoble.com" },
            new Profesor { Id = 22, Nombre= "Linda", Apellido = "Ramirez", Edad = 24, Correo = "lramirezl@bravesites.com" },
            new Profesor { Id = 23, Nombre= "Lillian", Apellido = "Lynch", Edad = 39, Correo = "llynchm@thetimes.co.uk" },
            new Profesor { Id = 24, Nombre= "Christopher", Apellido = "Jackson", Edad = 54, Correo = "" },
            new Profesor { Id = 25, Nombre= "Laura", Apellido = "Williams", Edad = 67, Correo = "" },
            new Profesor { Id = 26, Nombre= "William", Apellido = "Allen", Edad = 16, Correo = "wallenp@army.mil" },
            new Profesor { Id = 27, Nombre= "Henry", Apellido = "Arnold", Edad = 33, Correo = "harnoldq@exblog.jp" },
            new Profesor { Id = 28, Nombre= "Nancy", Apellido = "Peters", Edad = 39, Correo = "npetersr@engadget.com" },
            new Profesor { Id = 29, Nombre= "Janet", Apellido = "Torres", Edad = 50, Correo = "storress@npr.org" },
            new Profesor { Id = 30, Nombre= "Ruth", Apellido = "Williams", Edad = 26, Correo = "rbishopt@ezinearticles.com" },
        };
    }
}
